### ISSUE TITLE
Exponential notation validation

### ISSUE THREAD

**Issue by silentvick** [Litipk/php-bignumbers#7]
Hello!

The Decimal class throws an exception on numbers like these:
```
1.048576E+06 // leading zero
3.14E+00     // just zero
```
But it's a valid form. So I think they should be handled well.

**Comment by castarco** [comment]
Hi @silentvick , I haven't touched this code since long ago, and I don't remember exactly what assumptions I've made... I should take a look on this.

I'll be thankful if you split this issue in two issues, since the big exponential problem is a completely different problem.

Have you any proposal to fix any of these problems?

P.D.:
Long time ago I though on creating a new, more general and cleaner library to handle more number types in a more rigorous way (I want to carefully split the number types of their representations). The repository exists, it's called "MagicTheorist", but i can't find time to do it :( .

**Comment by silentvick** [comment]
@castarco , I've split issues, sorry for that. 

I'll look into fix. It shouldn't be too difficult.
